<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.5</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.duplessis.etienne</groupId>
    <artifactId>patchmaker</artifactId>
    <version>1.0.0</version>
    <name>patchmaker</name>
    <description>Demo project for Spring Boot</description>

    <properties>
        <java.version>17</java.version>
        <log4j2.version>2.20.0</log4j2.version>
        <spring-boot.version>3.3.5</spring-boot.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-rest</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-freemarker</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-1.2-api</artifactId>
            <version>${log4j2.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>${log4j2.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.junit.vintage</groupId>
                    <artifactId>junit-vintage-engine</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.restdocs</groupId>
            <artifactId>spring-restdocs-mockmvc</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-dbcp2</artifactId>
            <version>2.7.0</version>
        </dependency>
        <dependency>
            <groupId>commons-configuration</groupId>
            <artifactId>commons-configuration</artifactId>
            <version>1.9</version>
        </dependency>




        <!-- Oracle JDBC and JMS Driver -->
        <dependency>
            <groupId>com.oracle.database.jdbc</groupId>
            <artifactId>ojdbc8</artifactId>
            <version>21.5.0.0</version>
        </dependency>


        <!-- Lombok -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>

<!--    <build>-->
<!--        <plugins>-->

<!--            <plugin>-->
<!--                <groupId>org.codehaus.mojo</groupId>-->
<!--                <artifactId>appassembler-maven-plugin</artifactId>-->
<!--                <version>2.1.0</version>-->
<!--                <configuration>-->
<!--                    <repositoryLayout>flat</repositoryLayout>-->
<!--                    <includeConfigurationDirectoryInClasspath>true</includeConfigurationDirectoryInClasspath>-->
<!--                    <useWildcardClassPath>true</useWildcardClassPath>-->
<!--                    <target>${project.build.directory}</target>-->
<!--                    <daemons>-->
<!--                        <daemon>-->
<!--                            <id>patchmaker</id>-->
<!--                            <mainClass>com.duplessis.etienne.patchmaker.PatchmakerApplication</mainClass>-->
<!--                            <commandLineArguments>-->
<!--                                <commandLineArgument>start</commandLineArgument>-->
<!--                            </commandLineArguments>-->
<!--                            <platforms>-->
<!--                                <platform>jsw</platform>-->
<!--                            </platforms>-->
<!--                            <generatorConfigurations>-->
<!--                                <generatorConfiguration>-->
<!--                                    <generator>jsw</generator>-->
<!--                                    <includes>-->
<!--                                        <include>linux-x86-64</include>-->
<!--                                        <include>macosx-universal-64</include>-->
<!--                                        <include>windows-x86-64</include>-->
<!--                                    </includes>-->
<!--                                    <configuration>-->
<!--                                        <property>-->
<!--                                            <name>configuration.directory.in.classpath.first</name>-->
<!--                                            <value>conf</value>-->
<!--                                        </property>-->
<!--                                        <property>-->
<!--                                            <name>set.default.REPO_DIR</name>-->
<!--                                            <value>lib</value>-->
<!--                                        </property>-->
<!--                                        <property>-->
<!--                                            <name>wrapper.logfile</name>-->
<!--                                            <value>logs/wrapper.log</value>-->
<!--                                        </property>-->
<!--                                    </configuration>-->
<!--                                </generatorConfiguration>-->
<!--                            </generatorConfigurations>-->
<!--                            <jvmSettings>-->
<!--                                <initialMemorySize>128M</initialMemorySize>-->
<!--                                <maxMemorySize>1024M</maxMemorySize>-->
<!--                                <systemProperties>-->
<!--                                    <systemProperty>java.security.policy=conf/policy.all</systemProperty>-->
<!--                                </systemProperties>-->
<!--                            </jvmSettings>-->
<!--                        </daemon>-->
<!--                    </daemons>-->
<!--                </configuration>-->
<!--                <executions>-->
<!--                    <execution>-->
<!--                        <id>generate-jsw-scripts</id>-->
<!--                        <phase>package</phase>-->
<!--                        <goals>-->
<!--                            <goal>generate-daemons</goal>-->
<!--                        </goals>-->
<!--                    </execution>-->
<!--                </executions>-->
<!--            </plugin>-->
<!--        </plugins>-->
<!--    </build>-->

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring-boot.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
