#filepath=C:/Users/etien/Documents/installscripts/
#filepath=C:/Users/duple/Documents/installscripts
#patchPath=C:/Users/duple/Documents/installscripts
filepath=/doc/installscripts/
patchPath=/doc/installscripts/

# Oracle JMS Configuration
oracle.jms.username=your_username
oracle.jms.password=your_password
oracle.jms.url=jdbc:oracle:thin:@localhost:1521:yourSID